### ISSUE TITLE
这个框架会集成分库分表的内容吗？

### ISSUE THREAD

**Issue by liwei-swust** [automvc/bee#10]

**Comment by automvc** [comment]
你好，这个内容有考虑，包括redis的支持等，计划在v2.0版本添加。谢谢你的建议，也欢迎加入到Bee框架的开发之中！

**Comment by liwei-swust** [comment]
想参与其中，但是你们并没有把下个版本的issues公布出来，所以并不知道怎么参与

**Comment by automvc** [comment]
> 想参与其中，但是你们并没有把下个版本的issues公布出来，所以并不知道怎么参与

谢谢你的关注.  可以将你的建议发到Bee的联系邮箱，我们细聊！    honeysoft@126.com

**Comment by automvc** [comment]
仅分库；读写分离 已实现，请更新至 V1.8 或最新版 v1.8.15.

**Comment by automvc** [comment]
仅分库；读写分离一主多从；同库分表支持,动态表名映射支持 已实现，请更新至 V1.8 或最新版 v1.8.15.

**Comment by automvc** [comment]
仅分库；读写分离一主多从；同库分表,动态表名映射支持 已实现，请更新至 V1.8 或最新版 v1.8.15.
