### ISSUE TITLE
请问一下作者大大有没有打算搞个github上可以编辑的代码文档类似于Vue的文档那样

### ISSUE THREAD

**Issue by LiuXin8835** [automvc/bee#39]
如题，希望作者大大可以考虑搞个在github上可以上传的文档，我知道作者大大没时间弄复杂的文档，但是如果一个给别人用的框架没有文档别人会很难受，也不是每个人都有时间直接逆向源码（虽然看代码是最简单的方式，但是不给注释可以逼疯一票程序员），所以希望作者大致弄个可以在github或者gitbee上面编辑的文档就行了。
Bee ORM框架确实挺小挺好用的，尤其自动挡当作半自动挡开的时候（指数据源直接手动指定，剩下给Bee ORM搞），所以希望可以完善一下文档
可以使用docsify之内的去弄（官网：https://docsify.js.org/#/?id=docsify-4121）
CSDN上的教程：https://blog.csdn.net/Lonelyooacz/article/details/103439770

**Comment by xfl12345** [comment]
哈哈哈哈，附议 +1

**Comment by 1061302569** [comment]
nice啊，感觉Bee的社区太小众了

**Comment by xfl12345** [comment]
It have not completed yet.
