### ISSUE TITLE
How to multi-table, complex query

### ISSUE THREAD

**Issue by StormEagleLin** [automvc/bee#4]
How to multi-table, complex query

**Comment by automvc** [comment]
In current version,you can use custom define sql,or write the sql via the java chain style coding.
If you want to use the Bee feature (Coding Complexity is O(1)),you can define a view for your complex sql.

**Comment by automvc** [comment]
**V1.7**  
more tables select oriented object support.  
1.support one to one,one to many,many to one,many to many.  
2.support join(inner join), left join,right join, no join.  
3.The select operations of single table and more tables do not affect each other.
