### ISSUE TITLE
是否支持insert...on duplicate key update操作

### ISSUE THREAD

**Issue by smartian1** [automvc/bee#41]
请问是否支持insert...on duplicate key update操作？

**Comment by automvc** [comment]
Q: Bee为什么没有save方法?  
A: 别的ORM框架，将insert与update合为一个save方法，每次操作前都要查询一次数据，看数据库是否存在该记录，  
  以确定是要用insert还是update. 更新操作时，entity要设置id值，以便让查询确定该实体是否存在。  
  相当于更新操作，只能以id为where 条件,一次只能更新一条(有更新多条的需要时，这种做法效率不会高)。  
  当使用mysql数据库且JPA主键策略为@GeneratedValue(strategy = GenerationType.IDENTITY)，全局更新未带version数据时，  
  更新操作会变为保存操作。  
  但在很多业务场景，insert与update是明确可以区分开的，特别是在互联网应用。  
  要是用save反而会降低系统的性能。  
  如果确实有需要，可自己封装一个，参考:  
 
 ```java 
    	public int save(Orders orders) {
    	     if(orders==null) return 0;
    	     if(orders.getId()==null) return suidRich.insert(orders);
		Orders one = suidRich.selectById(orders, orders.getId());
		if (one != null)
			return suidRich.update(orders);
		else
			return suidRich.insert(orders);
	}  
 ```

**Comment by automvc** [comment]
/**
	 * 保存一个实体(一条记录).save one entity(one record).
	 * 如果可以区分开,建议明确调用insert(entity)或者update(entity),这样更加安全和高效.
	 * If it can be distinguished, it is recommended to explicitly call insert (entity) 
	 * <br>or update (entity), which is more secure and efficient.
	 * @param entity
	 * @return 返回受影响的行数,若失败则返回小于0的整数.the numbers of effect record(s),if fails, return integer less than 0.
	 * @since 1.9.8
	 */
	public <T> int save(T entity);
