### ISSUE TITLE
moretable无法正常获得关联后结果

### ISSUE THREAD

**Issue by praynise** [automvc/bee#44]
使用语言为kotlin
code:
```
data class Systems(
    var systemId: Int? = null, //系统ID
    var systemEnName: String? = null, //系统英文名称
    var systemCnName: String? = null, //系统中文名称
    @JoinTable(mainField="system_id", subField="system_id", joinType=JoinType.LEFT_JOIN)
    var hosts : Hosts? = null
) : Serializable

data class Hosts(
    var hostId: Int? = null, //主机ID
    var systemId: Int? = null, //主机对应系统ID
    var hostIp: String? = null, //主机IP地址
    var hostFileTransferPort: String? = null, //主机文件传输端口
    var hasClient: Int? = null, //是否部署了客户端
    var loginUser: String? = null, //连接用户
    var loginPassword: String? = null, //连接密码码
    var remark: String? = null, //备注
    var isOnline : Int ?= null //主机是否在线
) : Serializable

fun main() {
    val suid: Suid = BeeFactory.getHoneyFactory().suidRich
    println(suid.select(Systems(systemId = 1)))
    println(suid.select(Hosts(hostId = 1)))
    val moreTable = BeeFactory.getHoneyFactory().moreTable
    println(moreTable.select(Systems(systemId = 1)))
}
```
输出：
[Bee] LoggerFactory Use the Logger is : org.teasoft.honey.logging.SystemLogger
2021-08-04 15:08:38 [Bee] ========= get the dbName from HoneyConfig is :MOGDB
2021-08-04 15:08:38 [Bee] select SQL: select system_id,system_en_name,system_cn_name from systems where system_id=?   [values]: 1
八月 04, 2021 3:08:38 下午 org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
信息: [cbc6c65e-d8b0-4921-96d0-bff6749186d4] Try to connect. IP: 110.128.5.111:5432
八月 04, 2021 3:08:39 下午 org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
信息: [170.128.15.36:54563/110.128.5.111:5432] Connection is established. ID: cbc6c65e-d8b0-4921-96d0-bff6749186d4
八月 04, 2021 3:08:39 下午 org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
信息: Connect complete. ID: cbc6c65e-d8b0-4921-96d0-bff6749186d4
2021-08-04 15:08:39 [Bee]  | <--  select rows: 1
[Systems(systemId=1, systemEnName=FST, systemCnName=第一测试系统, hosts=null)]
2021-08-04 15:08:39 [Bee] select SQL: select host_id,system_id,host_ip,host_file_transfer_port,has_client,login_user,login_password,remark,is_online from hosts where host_id=?   [values]: 1
八月 04, 2021 3:08:39 下午 org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
信息: [cab8dff1-fd14-41ee-bfb4-b61d62f7c88f] Try to connect. IP: 110.128.5.111:5432
八月 04, 2021 3:08:39 下午 org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
信息: [170.128.15.36:54564/110.128.5.111:5432] Connection is established. ID: cab8dff1-fd14-41ee-bfb4-b61d62f7c88f
八月 04, 2021 3:08:39 下午 org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
信息: Connect complete. ID: cab8dff1-fd14-41ee-bfb4-b61d62f7c88f
八月 04, 2021 3:08:39 下午 org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
信息: [b37353b8-57f1-4483-8ead-866a12fa9e9b] Try to connect. IP: 110.128.5.111:5432
2021-08-04 15:08:39 [Bee]  | <--  select rows: 1
[Hosts(hostId=1, systemId=1, hostIp=110.128.5.111, hostFileTransferPort=3333, hasClient=1, loginUser=usera, loginPassword=apass, remark=应用服务器, isOnline=1)]
2021-08-04 15:08:39 [Bee] select SQL: select systems.system_id,systems.system_en_name,systems.system_cn_name,hosts.host_id,hosts.system_id,hosts.host_ip,hosts.host_file_transfer_port,hosts.has_client,hosts.login_user,hosts.login_password,hosts.remark,hosts.is_online from systems left join hosts on systems.system_id=hosts.system_id where systems.system_id=?   [values]: 1
八月 04, 2021 3:08:39 下午 org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
信息: [170.128.15.36:54565/110.128.5.111:5432] Connection is established. ID: b37353b8-57f1-4483-8ead-866a12fa9e9b
八月 04, 2021 3:08:39 下午 org.postgresql.core.v3.ConnectionFactoryImpl openConnectionImpl
信息: Connect complete. ID: b37353b8-57f1-4483-8ead-866a12fa9e9b
2021-08-04 15:08:39 [Bee]  | <--  select rows: 1
[Systems(systemId=null, systemEnName=null, systemCnName=null, hosts=Hosts(hostId=null, systemId=null, hostIp=null, hostFileTransferPort=null, hasClient=null, loginUser=null, loginPassword=null, remark=null, isOnline=null))]

Process finished with exit code 0

可以看到我在查询单表的时候都可以成功，但是当使用moreTable进行查询的时候，却无法关联到，烦请指点，非常感谢~

**Comment by automvc** [comment]
模拟了使用场景,  没有重现相关问题.  
参考以下详细例子:
https://blog.csdn.net/abckingaa/article/details/120743630
注: 子类List类型在V1.9.8开始支持.
