### ISSUE TITLE
entity中非null且非空字符串将插入到数据库

### ISSUE THREAD

**Issue by wangyuanfei** [automvc/bee#46]
null 过滤掉可以理解
空字符串感觉并不用过滤
比我 desc 字段表示自我介绍， null 就是从来没有设置过，『你好我叫xxx』 这个是有值状态，   空字符串表示 我把自我介绍删除了，但是我曾经设置过。
insertAndReturnId 把includeType 写死成-1了，会导致 null 和 空字符串都过滤掉了
不知道我理解的对不对，或者配合数据库有比较好的方案设计，请多指教

**Comment by automvc** [comment]
Suid接口默认是过虑null和空字符的.
若不需要返回id,可以使用SuidRich的方法:
public <T> int insert(T entity,IncludeType includeType);
下个版本会考虑添加个方法:
public <T> long insertAndReturnId(T entity,IncludeType includeType);

对于你的问题:
" 空字符串表示 我把自我介绍删除了，但是我曾经设置过。"   那就是插入数据时是初始化,还没有删除该字段的事发生,不可能有空字符.  若要将对应字段置为空, 使用SuidRich的相应update方法即可.

**Comment by wangyuanfei** [comment]
嗯 知道了，谢谢耐心解答
