### ISSUE TITLE
ConditionImpl使用in条件报错

### ISSUE THREAD

**Issue by hardill** [automvc/bee#55]
当字段为int类型时,condition.op("id", Op.in,list); sql拼接报错,ERROR: operator does not exist: integer = character varying,

**Comment by automvc** [comment]
V1.17 (V1.17.0.9)

8)condition.op(fieldName, Op.in, Value)增加支持List,Set,Number Array,单个Number元素  
9)condition.opOn(fieldName, Op.in, Value) Value限定只支持Number和String
